# Generated by Django 3.0.2 on 2021-06-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userprofile_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='questionPaperAttended',
            new_name='questionPapersAttended',
        ),
    ]
