# Generated by Django 3.0.2 on 2021-06-06 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0001_initial'),
        ('user', '0005_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaperattended',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assesment.questionPaper'),
        ),
    ]
